[package]
name = "resolver_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#[dependencies.windows]
#version = "0.35.0"
#features = [
#    "Win32_Media",
#    "Win32_Media_DeviceManager"
#]
